const routes = {
	home: "/",
	contact: "/contact",
	verifyOTP: "/verify-otp",
	forgetPassword: "/forget-password",
	passwordresetconfirmation: "/password-reset-confirmation",
	resetPassword:"/reset-password",
	login: "/login",
	studentLogin: "/student-login",
	register: "/register",
	about: "/about",
	awards: "/awards",
	blog: "/blog",
	blogPost: (title) => `/blog/${title}`,
	dashboard: "/dashboard",
	newPage: "/new",
	notFound: "*",
	userDashboard: "/user/dashboard",
	buyProduct: "/user/buy-product",
	viewProduct: "/user/view-product",
	orderSummary: "/user/payment-summary",
	paymentSuccess: "/user/payment-success",
	Congrats: "/user/congrats",
	userNotification: "/user/notification",
	userMyAccount: "/user/my-account",
	userResetPassword: "/user/reset-password",
	ourFeatures: "/user/our-features",
	pricePlan: "/user/price-plan",
	productHistory: "/user/product-history",
	ManageRegisteredProduct: "/user/manage-registered-product",
	upgradeSubscription: "/user/upgrade-subscription",
	adminDashboard: "/admin-main",
	addFAQ: "/add-faq",
	manageFAQ: "/manage-faq",
	addSubscription: "/add-subscription",
	manageSubscription: "/manage-subscription",
	addTestimony: "/add-testimony",
	manageTestimony: "/manage-testimony",
	addProduct: "/add-product",
	manageProduct: "/manage-product",
	adminResetPassword: "/admin/reset-password",
	adminMyAccount: "/admin/my-account",
	aboutEdit: "/about/edit",
	contactEdit: "/contact/edit",
	addBlog: "/add-blog",
	manageBlog: "/manage-blog",
	addCoupon: "/add-coupon",
	manageCoupon: "/manage-coupon",
	schoolManagement: "/school-management",
	schoolContact: "/school-management/contact",
	schoolAbout: "/school-management/about",
	schoolStaff: "/school-management/staff",
	schoolPortal: "/school-management/portal",
	schoolApply: "/school-management/apply",
	studentBio: "/school-management/apply/student-bio",
	studentEdulevel: "/school-management/apply/education-level",
	student: "/student",
	// Parent Portal Routes
	parentDashboard: "/parent",
	parentChildren: "/parent/children/view",
	parentChildrenProgress: "/parent/children/progress",
	parentChildrenAttendance: "/parent/children/attendance",
	parentChildrenResults: "/parent/children/results",
	parentPaymentsSchoolFees: "/parent/payments/school-fees",
	parentPaymentsUpgrade: "/parent/payments/upgrade",
	parentPaymentsHistory: "/parent/payments/history",
	parentPaymentsFeeStructure: "/parent/payments/fee-structure",
	parentCommunicationMessages: "/parent/communication/messages",
	parentCommunicationAnnouncements: "/parent/communication/announcements",
	parentCommunicationTeachers: "/parent/communication/teachers",
	parentAcademicTimetable: "/parent/academic/timetable",
	parentAcademicAssignments: "/parent/academic/assignments",
	parentAcademicExams: "/parent/academic/exams",
	parentSettingsProfile: "/parent/settings/profile",
	parentSettingsNotifications: "/parent/settings/notifications",
	// Attendance System Routes
	adminAttendance: "/admin/attendance",
	teacherAttendance: "/teacher/attendance",
	studentAttendance: "/student/attendance",
	attendanceDemo: "/attendance/demo",
	// EduOS Subscription Flow
	subscriptionPlans: "/choose-plan",
	payment: "/payment",
	paymentSuccessEduos: "/payment-success",
	schoolDetails: "/school-details",
	// Accountant Routes
	accountantDashboard: "/accountant",
	accountantAttendance: "/accountant/attendance",
	accountantAttendanceStaff: "/accountant/attendance/staff",
	accountantAttendanceQR: "/accountant/attendance/qr-code",
	accountantAttendanceNFC: "/accountant/attendance/nfc",
	accountantAttendanceFacial: "/accountant/attendance/facial-recognition",
	accountantAttendanceManual: "/accountant/attendance/manual-log",
	accountantAttendanceReports: "/accountant/attendance/reports",
	// Admin Accountant Management
	adminAccountantIDCards: "/admin/staff/accountant-id-cards",
};

export default routes;
