const routes = {
	home: "/",
	contact: "/contact",
	verifyOTP: "/verify-otp",
	forgetPassword: "/forget-password",
	passwordresetconfirmation: "/password-reset-confirmation",
	resetPassword:"/reset-password",
	login: "/login",
	studentLogin: "/student-login",
	register: "/register",
	about: "/about",
	blog: "/blog",
	blogPost: (title) => `/blog/${title}`,
	dashboard: "/dashboard",
	newPage: "/new",
	notFound: "*",
	userDashboard: "/user/dashboard",
	buyProduct: "/user/buy-product",
	viewProduct: "/user/view-product",
	orderSummary: "/user/payment-summary",
	paymentSuccess: "/user/payment-success",
	Congrats: "/user/congrats",
	userNotification: "/user/notification",
	userMyAccount: "/user/my-account",
	userResetPassword: "/user/reset-password",
	ourFeatures: "/user/our-features",
	pricePlan: "/user/price-plan",
	productHistory: "/user/product-history",
	ManageRegisteredProduct: "/user/manage-registered-product",
	adminDashboard: "/admin",
	addFAQ: "/add-faq",
	manageFAQ: "/manage-faq",
	addSubscription: "/add-subscription",
	manageSubscription: "/manage-subscription",
	addTestimony: "/add-testimony",
	manageTestimony: "/manage-testimony",
	addProduct: "/add-product",
	manageProduct: "/manage-product",
	adminResetPassword: "/admin/reset-password",
	adminMyAccount: "/admin/my-account",
	aboutEdit: "/about/edit",
	contactEdit: "/contact/edit",
	addBlog: "/add-blog",
	manageBlog: "/manage-blog",
	schoolManagement: "/school-management",
	schoolContact: "/school-management/contact",
	schoolAbout: "/school-management/about",
	schoolStaff: "/school-management/staff",
	schoolPortal: "/school-management/portal",
	schoolApply: "/school-management/apply",
	studentBio: "/school-management/apply/student-bio",
	studentEdulevel: "/school-management/apply/education-level",
	student: "/student",
	// EduOS Subscription Flow
	subscriptionPlans: "/choose-plan",
	payment: "/payment",
	paymentSuccessEduos: "/payment-success",
	schoolDetails: "/school-details",
};

export default routes;
